FROM public.ecr.aws/lambda/python:3.14

COPY app/ ${LAMBDA_TASK_ROOT}/app/
COPY trackly/ ${LAMBDA_TASK_ROOT}/trackly/
COPY scripts/ ${LAMBDA_TASK_ROOT}/scripts/

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r requirements.txt

CMD [ "app.handler.handler" ]
