"use client";

import React from "react";
import Link from "next/link";
import Image from "next/image";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
import { List } from "@phosphor-icons/react";
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

type NavGroup = {
  group: string;
  items: string[];
};

type ParamSpec = {
  name: string;
  type: string;
  required?: boolean;
  defaultValue?: string;
  description: string;
  example?: string;
};

const NAV: NavGroup[] = [
  {
    group: "Start here",
    items: [
      "Introduction",
      "Installation",
      "Quickstart",
      "Trackly constructor",
      "Environment variables",
    ],
  },
  {
    group: "LangChain",
    items: ["Callbacks", "LangChain provider examples"],
  },
  {
    group: "Native SDKs",
    items: ["Introduction to native SDKs"],
  },
  {
    group: "Individual SDK Support",
    items: [
      "Anthropic messages",
      "Gemini models",
      "Gemini batches",
      "Ollama native",
      "Ollama async + utilities",
    ],
  },
  {
    group: "Operations",
    items: ["Debug and shutdown", "Self-hosting"],
  },
  {
    group: "Backend API",
    items: [
      "Ingest API",
      "Events API",
      "Stats API",
      "Organizations and projects",
      "API keys",
    ],
  },
];

const CONSTRUCTOR_PARAMS: ParamSpec[] = [
  {
    name: "provider",
    type: "str | None",
    required: false,
    defaultValue: "None",
    description:
      "Use this when you want Trackly's native wrappers. The built-in values are `providers.LANGCHAIN`, `providers.OLLAMA`, and `providers.GEMINI`. For normal LangChain callbacks you can leave it unset.",
    example: "Trackly(provider=providers.OLLAMA)",
  },
  {
    name: "api_key",
    type: "str | None",
    required: false,
    defaultValue: "TRACKLY_API_KEY",
    description:
      "Bearer key used when Trackly ships events to your Trackly backend. If this is missing, tracking stays disabled unless you provide it later through the environment.",
    example: 'Trackly(api_key="tk_live_...")',
  },
  {
    name: "base_url",
    type: "str | None",
    required: false,
    defaultValue: "TRACKLY_BASE_URL or SDK default",
    description:
      "Base URL for your Trackly backend. The worker automatically appends `/events` when needed, so pass your API root such as `https://your-host/api/v1`.",
    example: 'Trackly(base_url="https://trackly.example.com/api/v1")',
  },
  {
    name: "debug",
    type: "bool",
    required: false,
    defaultValue: "False",
    description:
      "Prints enqueue, retry, and send status logs to help you debug ingestion and API key problems.",
    example: "Trackly(debug=True)",
  },
  {
    name: "feature",
    type: "str",
    required: false,
    defaultValue: '"default"',
    description:
      "Default feature tag attached to every event generated by this Trackly instance.",
    example: 'Trackly(feature="support-chat")',
  },
  {
    name: "environment",
    type: "str",
    required: false,
    defaultValue: '"production"',
    description:
      "Default environment label attached to every event, useful for separating dev, staging, and production traffic.",
    example: 'Trackly(environment="staging")',
  },
  {
    name: "gemini_api_key",
    type: "str | None",
    required: false,
    defaultValue: "GEMINI_API_KEY",
    description:
      "Credential used by `trackly.models` and `trackly.batches` when you use the native Gemini wrappers.",
    example: 'Trackly(provider=providers.GEMINI, gemini_api_key="AIza...")',
  },
  {
    name: "anthropic_api_key",
    type: "str | None",
    required: false,
    defaultValue: "ANTHROPIC_API_KEY",
    description:
      "Credential used by `trackly.messages` when you use the native Anthropic wrappers.",
    example:
      'Trackly(provider=providers.ANTHROPIC, anthropic_api_key="sk-ant-...")',
  },
];

const ENV_VARS: ParamSpec[] = [
  {
    name: "TRACKLY_API_KEY",
    type: "string",
    description:
      "Default Trackly ingestion key. This is the main secret the background worker sends in the `Authorization` header.",
    example: "TRACKLY_API_KEY=tk_live_your_key_here",
  },
  {
    name: "TRACKLY_BASE_URL",
    type: "string",
    description:
      "Overrides the backend base URL for self-hosting or local development.",
    example: "TRACKLY_BASE_URL=http://localhost:8000/api/v1",
  },
  {
    name: "TRACKLY_DEBUG",
    type: "string",
    description:
      "Set this to `1` to enable verbose worker logs without changing application code.",
    example: "TRACKLY_DEBUG=1",
  },
  {
    name: "GEMINI_API_KEY",
    type: "string",
    description: "Default Gemini credential for the native Gemini wrappers.",
    example: "GEMINI_API_KEY=AIza_your_gemini_key",
  },
  {
    name: "ANTHROPIC_API_KEY",
    type: "string",
    description:
      "Default Anthropic credential for the native Anthropic wrappers.",
    example: "ANTHROPIC_API_KEY=sk-ant-your_anthropic_key",
  },
];

const INGEST_FIELDS: ParamSpec[] = [
  {
    name: "provider",
    type: "string",
    required: true,
    description:
      "Canonical provider name such as `openai`, `anthropic`, `google`, `ollama`, or `google-batch`.",
    example: '"provider": "openai"',
  },
  {
    name: "model",
    type: "string",
    required: true,
    description:
      "The exact model name used for the request. Cost lookup depends on this field.",
    example: '"model": "gpt-4o"',
  },
  {
    name: "prompt_tokens",
    type: "int | null",
    description:
      "Input token count. Send this when your provider exposes separate prompt usage.",
    example: '"prompt_tokens": 1200',
  },
  {
    name: "completion_tokens",
    type: "int | null",
    description:
      "Output token count. Send this when your provider exposes separate completion usage.",
    example: '"completion_tokens": 280',
  },
  {
    name: "total_tokens",
    type: "int | null",
    description:
      "Total token count. If you omit it but send prompt and completion tokens, the backend computes the total automatically.",
    example: '"total_tokens": 1480',
  },
  {
    name: "latency_ms",
    type: "int | null",
    description: "Latency in milliseconds for the model call or batch action.",
    example: '"latency_ms": 842',
  },
  {
    name: "finish_reason",
    type: "string | null",
    description:
      "Provider finish reason such as `stop`, `length`, `STOP`, or `embedding`.",
    example: '"finish_reason": "stop"',
  },
  {
    name: "run_id",
    type: "string | null",
    description:
      "Primary trace identifier for a single model call. Useful when you stitch events back to application logs.",
    example: '"run_id": "run_123"',
  },
  {
    name: "parent_run_id",
    type: "string | null",
    description:
      "Optional parent trace identifier for nested chains and agents.",
    example: '"parent_run_id": "chain_abc"',
  },
  {
    name: "feature",
    type: "string | null",
    description:
      "Application feature label like `chat`, `summary`, or `rag-search`.",
    example: '"feature": "invoice-summary"',
  },
  {
    name: "user_id",
    type: "string | null",
    description:
      "Your own user identifier. It can be a plain string, Auth0 id, or UUID.",
    example: '"user_id": "auth0|abc123"',
  },
  {
    name: "session_id",
    type: "string | null",
    description: "Conversation or session identifier for grouping events.",
    example: '"session_id": "chat-session-44"',
  },
  {
    name: "environment",
    type: "string | null",
    description:
      "Deployment environment such as `dev`, `staging`, or `production`.",
    example: '"environment": "production"',
  },
  {
    name: "tags",
    type: "list[str]",
    description: "Small filterable labels for manual or custom events.",
    example: '"tags": ["trial-user", "beta"]',
  },
  {
    name: "extra",
    type: "dict[str, Any]",
    description:
      "Free-form JSON metadata for any custom context you want to keep with the event.",
    example: '"extra": {"route": "/chat", "tenant": "acme"}',
  },
  {
    name: "sdk_version",
    type: "string | null",
    description: "Version string for your SDK or ingestion client.",
    example: '"sdk_version": "0.1.3"',
  },
  {
    name: "timestamp",
    type: "datetime | null",
    description:
      "When the event actually happened. If omitted, the backend uses the current UTC time.",
    example: '"timestamp": "2026-03-25T19:15:00Z"',
  },
];

const EVENTS_QUERY_PARAMS: ParamSpec[] = [
  {
    name: "feature",
    type: "string | null",
    description: "Return only events for one feature label.",
    example: "?feature=support-chat",
  },
  {
    name: "user_id",
    type: "string | null",
    description:
      "Filter by a raw user id, Auth0 id, or UUID. The backend tries to match all of them.",
    example: "?user_id=auth0|abc123",
  },
  {
    name: "model",
    type: "string | null",
    description: "Return only one model.",
    example: "?model=gpt-4o",
  },
  {
    name: "provider",
    type: "string | null",
    description: "Return only one provider.",
    example: "?provider=openai",
  },
  {
    name: "api_key_id",
    type: "uuid | null",
    description:
      "Find events created by a master key or one of its derived access keys.",
    example: "?api_key_id=6f3b3f0b-...",
  },
  {
    name: "start",
    type: "datetime | null",
    description: "Inclusive UTC start timestamp.",
    example: "?start=2026-03-01T00:00:00Z",
  },
  {
    name: "end",
    type: "datetime | null",
    description: "Exclusive UTC end timestamp.",
    example: "?end=2026-04-01T00:00:00Z",
  },
  {
    name: "page",
    type: "int",
    defaultValue: "1",
    description: "1-based page number.",
    example: "?page=2",
  },
  {
    name: "page_size",
    type: "int",
    defaultValue: "50",
    description: "Page size from 1 to 200.",
    example: "?page_size=100",
  },
];

const STATS_QUERY_PARAMS: ParamSpec[] = [
  {
    name: "project_id",
    type: "uuid",
    required: true,
    description: "Path parameter for the project you want to query.",
    example: "/api/v1/projects/6f3b3f0b-.../stats/summary",
  },
  {
    name: "provider",
    type: "string | null",
    description:
      "Optional provider filter for `summary`, `by-model`, `by-feature`, and `daily`.",
    example: "?provider=openai",
  },
  {
    name: "start",
    type: "datetime | null",
    description:
      "Optional UTC start time. When omitted, Trackly uses 30 days before now.",
    example: "?start=2026-03-01T00:00:00Z",
  },
  {
    name: "end",
    type: "datetime | null",
    description:
      "Optional UTC end time. When omitted, Trackly uses the current UTC time.",
    example: "?end=2026-03-25T00:00:00Z",
  },
];

const ORG_AND_PROJECT_FIELDS: ParamSpec[] = [
  {
    name: "OrganizationCreate.name",
    type: "string",
    required: true,
    description: "Human-readable organization name.",
    example: '"name": "Acme AI"',
  },
  {
    name: "OrganizationCreate.slug",
    type: "string",
    required: true,
    description:
      "Lowercase slug. It must be alphanumeric with hyphens and cannot start or end with a hyphen.",
    example: '"slug": "acme-ai"',
  },
  {
    name: "ProjectCreate.name",
    type: "string",
    required: true,
    description: "Project name inside the organization.",
    example: '"name": "Production"',
  },
  {
    name: "ProjectCreate.environment",
    type: "string | null",
    description: "Optional environment stored on the project itself.",
    example: '"environment": "prod"',
  },
  {
    name: "ProjectMemberAdd.email",
    type: "string",
    required: true,
    description: "Email of the existing user you want to add to a project.",
    example: '"email": "teammate@example.com"',
  },
  {
    name: "ProjectMemberAdd.role",
    type: "string",
    defaultValue: '"member"',
    description: "Project role. The code defaults to `member`.",
    example: '"role": "admin"',
  },
  {
    name: "OrganizationMemberAdd.email",
    type: "string",
    required: true,
    description: "Email of the user to add or invite to the organization.",
    example: '"email": "new-user@example.com"',
  },
  {
    name: "OrganizationMemberAdd.name",
    type: "string | null",
    description:
      "Optional display name used if Trackly creates an invited placeholder user.",
    example: '"name": "Taylor Kim"',
  },
];

const API_KEY_FIELDS: ParamSpec[] = [
  {
    name: "ApiKeyCreate.name",
    type: "string",
    required: true,
    description: "Friendly label for the key shown in the dashboard.",
    example: '"name": "Server key"',
  },
  {
    name: "ApiKeyCreate.project_id",
    type: "uuid | null",
    description:
      "Scope the key to a project. The ingest endpoint requires a project-scoped key.",
    example: '"project_id": "6f3b3f0b-..."',
  },
  {
    name: "ApiKeyCreate.created_by_user_id",
    type: "uuid | null",
    description:
      "Optional creator id used by the permission checks for org admins and project admins.",
    example: '"created_by_user_id": "4d7f9ef8-..."',
  },
  {
    name: "ApiKeyAccessRequest.auth0_id",
    type: "string",
    required: true,
    description:
      "Auth0 id of the user who should receive a derived access key.",
    example: '"auth0_id": "auth0|abc123"',
  },
  {
    name: "auth0_id query parameter",
    type: "string",
    description:
      "Used by the list and revoke endpoints to apply visibility and permission rules.",
    example: "?auth0_id=auth0|abc123",
  },
];

const LANGCHAIN_EXAMPLES = [
  {
    title: "OpenAI",
    install: 'pip install "trackly[openai]"',
    code: `from trackly import Trackly
from langchain_openai import ChatOpenAI

trackly = Trackly(
    api_key="tk_live_...",
    feature="support-chat",
    environment="production",
)

llm = ChatOpenAI(
    model="gpt-4o",
    callbacks=[trackly.callback()],
)

response = llm.invoke("Summarize the customer issue in one sentence.")
print(response.content)`,
  },
  {
    title: "Anthropic",
    install: 'pip install "trackly[anthropic]"',
    code: `from trackly import Trackly
from langchain_anthropic import ChatAnthropic

trackly = Trackly(feature="ticket-triage", environment="staging")

llm = ChatAnthropic(
    model="claude-3-5-sonnet-latest",
    callbacks=[trackly.callback()],
)

reply = llm.invoke("Classify this message into billing, bug, or feature request.")
print(reply.content)`,
  },
  {
    title: "Google Gemini",
    install: 'pip install "trackly[gemini]"',
    code: `from trackly import Trackly
from langchain_google_genai import ChatGoogleGenerativeAI

trackly = Trackly(feature="doc-qa", environment="production")

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    callbacks=[trackly.callback()],
)

answer = llm.invoke("Explain retrieval augmented generation in plain English.")
print(answer.content)`,
  },
  {
    title: "Groq",
    install: "pip install langchain-groq",
    code: `from trackly import Trackly
from langchain_groq import ChatGroq

trackly = Trackly(feature="fast-drafts", environment="prod")

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    callbacks=[trackly.callback()],
)

result = llm.invoke("Write a three-bullet summary of vector databases.")
print(result.content)`,
  },
  {
    title: "Mistral",
    install: "pip install langchain-mistralai",
    code: `from trackly import Trackly
from langchain_mistralai import ChatMistralAI

trackly = Trackly(feature="analysis", environment="dev")

llm = ChatMistralAI(
    model="mistral-large-latest",
    callbacks=[trackly.callback()],
)

response = llm.invoke("Explain why token accounting matters.")
print(response.content)`,
  },
  {
    title: "Ollama via LangChain",
    install: 'pip install "trackly[ollama]"',
    code: `from trackly import Trackly
from langchain_ollama import ChatOllama

trackly = Trackly(feature="local-rag", environment="dev")

llm = ChatOllama(
    model="llama3.2",
    callbacks=[trackly.callback()],
)

response = llm.invoke("Give me a short explanation of embeddings.")
print(response.content)`,
  },
];

function Ic({ children }: { children: React.ReactNode }) {
  return (
    <code className="font-mono text-[.78rem] bg-[#11131a] border border-white/8 text-zinc-100 px-1.5 py-0.5 rounded-none">
      {children}
    </code>
  );
}

function CodeBlock({ lang, children }: { lang: string; children: string }) {
  const [copied, setCopied] = React.useState(false);

  function copy() {
    navigator.clipboard.writeText(children);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="bg-[#080a10] border border-white/8 rounded-none overflow-hidden my-4 shadow-[6px_6px_0_0_#000]">
      <div className="flex items-center justify-between px-3.5 py-2 border-b border-white/6 bg-white/3">
        <div className="flex items-center gap-2">
          <div className="flex gap-1.5">
            <span className="w-[9px] h-[9px] rounded-full bg-[#ff5f57]" />
            <span className="w-[9px] h-[9px] rounded-full bg-[#febc2e]" />
            <span className="w-[9px] h-[9px] rounded-full bg-[#28c840]" />
          </div>
          <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500">
            {lang}
          </span>
        </div>
        <button
          onClick={copy}
          className={`font-mono text-[10px] px-2 py-0.5 rounded-none border-2 transition-all ${
            copied
              ? "text-[#34d399] border-[#34d399] bg-[#34d399]/5"
              : "text-zinc-400 border-zinc-700 bg-[#141822] hover:text-white hover:border-white"
          }`}
        >
          {copied ? "COPIED" : "COPY"}
        </button>
      </div>
      <SyntaxHighlighter
        language={
          lang.toLowerCase().includes("python")
            ? "python"
            : lang.toLowerCase().includes("bash")
              ? "bash"
              : lang.toLowerCase().includes("json")
                ? "json"
                : lang.toLowerCase().includes("env")
                  ? "bash"
                  : "python"
        }
        style={vscDarkPlus}
        customStyle={{
          background: "transparent",
          padding: "1rem",
          margin: 0,
          fontSize: "12px",
          lineHeight: "1.55",
        }}
      >
        {children}
      </SyntaxHighlighter>
    </div>
  );
}

function Callout({
  type,
  children,
}: {
  type: "info" | "warn" | "success";
  children: React.ReactNode;
}) {
  const styles = {
    info: "bg-sky-500/[0.08] border-sky-400/25 text-sky-200",
    warn: "bg-amber-500/[0.08] border-amber-400/25 text-amber-200",
    success: "bg-emerald-500/[0.08] border-emerald-400/25 text-emerald-200",
  };

  const labels = {
    info: "INFO",
    warn: "NOTE",
    success: "GOOD",
  };

  return (
    <div
      className={`px-4 py-3 border-2 rounded-none text-[.82rem] leading-relaxed my-4 ${styles[type]}`}
    >
      <div className="font-bold text-[10px] tracking-[0.24em] uppercase mb-1">
        {labels[type]}
      </div>
      <div>{children}</div>
    </div>
  );
}

function SectionTitle({
  accentColor = "#f59e0b",
  children,
}: {
  accentColor?: string;
  children: React.ReactNode;
}) {
  return (
    <h2 className="text-[1.15rem] font-bold tracking-tight text-white mb-4 mt-8 flex items-center gap-3">
      <span
        className="w-2.5 h-2.5 rotate-45 shrink-0"
        style={{ backgroundColor: accentColor }}
      />
      {children}
    </h2>
  );
}

function Step({
  n,
  label,
  children,
}: {
  n: number;
  label: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-3 mb-2">
        <span className="w-7 h-7 rounded-none bg-[#f59e0b] text-black font-bold text-[11px] flex items-center justify-center shrink-0">
          {n}
        </span>
        <h3 className="text-[.9rem] font-bold text-zinc-100 uppercase tracking-wide">
          {label}
        </h3>
      </div>
      <div className="pl-10">{children}</div>
    </div>
  );
}

function ParameterGrid({ items }: { items: ParamSpec[] }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {items.map((item) => (
        <div
          key={item.name}
          className="border-2 border-white/8 bg-white/[0.03] p-4 shadow-[4px_4px_0_0_#000]"
        >
          <div className="flex items-start justify-between gap-4 mb-3">
            <Ic>{item.name}</Ic>
            <span
              className={`text-[10px] uppercase tracking-[0.22em] ${
                item.required ? "text-[#f59e0b]" : "text-zinc-500"
              }`}
            >
              {item.required ? "Required" : "Optional"}
            </span>
          </div>
          <p className="text-[.83rem] text-zinc-300 leading-relaxed">
            {item.description}
          </p>
          <div className="mt-4 space-y-1 text-[.74rem] text-zinc-400">
            <div>
              <span className="text-zinc-500">Type:</span> {item.type}
            </div>
            {item.defaultValue ? (
              <div>
                <span className="text-zinc-500">Default:</span>{" "}
                {item.defaultValue}
              </div>
            ) : null}
            {item.example ? (
              <div>
                <span className="text-zinc-500">Example:</span>{" "}
                <span className="text-zinc-200">{item.example}</span>
              </div>
            ) : null}
          </div>
        </div>
      ))}
    </div>
  );
}

function RouteBadge({ children }: { children: React.ReactNode }) {
  return (
    <div className="inline-flex items-center border border-white/10 bg-white/[0.04] px-3 py-1.5 text-[.8rem] text-zinc-200 font-mono uppercase tracking-[0.14em]">
      {children}
    </div>
  );
}

const DocsNav = ({
  activeNav,
  setActiveNav,
  onItemSelected,
}: {
  activeNav: string;
  setActiveNav: (name: string) => void;
  onItemSelected?: () => void;
}) => {
  return (
    <div className="flex flex-col gap-8">
      {NAV.map((group) => (
        <div key={group.group}>
          <h4 className="text-[10px] font-bold uppercase tracking-[0.22em] text-zinc-400 mb-4 px-2">
            {group.group}
          </h4>
          <nav className="flex flex-col gap-1.5">
            {group.items.map((item) => {
              const isActive = activeNav === item;
              return (
                <button
                  key={item}
                  onClick={() => {
                    setActiveNav(item);
                    onItemSelected?.();
                    window.scrollTo({ top: 0, behavior: "smooth" });
                  }}
                  className={`text-left px-4 py-3 text-[0.84rem] transition-all duration-200 cursor-pointer border-l-2 ${
                    isActive
                      ? "border-[#f59e0b] bg-white/[0.06] text-white translate-x-1"
                      : "border-transparent text-zinc-500 hover:text-zinc-200 hover:border-white/20"
                  }`}
                >
                  {item}
                </button>
              );
            })}
          </nav>
        </div>
      ))}
    </div>
  );
};

export default function DocsPage() {
  const [activeNav, setActiveNav] = React.useState("Introduction");
  const [isSidebarOpen, setIsSidebarOpen] = React.useState(false);

  const renderContent = () => {
    switch (activeNav) {
      case "Introduction":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Source-driven docs
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Introduction
            </h1>
            <p className="text-[.96rem] text-zinc-300 leading-[1.8] mb-6">
              Trackly is a Python usage-tracking layer for LLM apps. It hooks
              into LangChain callbacks or native Anthropic, Ollama, and Gemini
              SDK calls, then records provider, model, tokens, latency, and your
              own labels in the background.
            </p>

            <SectionTitle accentColor="#14b8a6">
              What Trackly records
            </SectionTitle>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[
                {
                  title: "Provider + model",
                  desc: "Trackly stores the provider name and exact model string so pricing and filtering stay accurate.",
                },
                {
                  title: "Token usage",
                  desc: "Prompt, completion, and total tokens are captured when the provider exposes them.",
                },
                {
                  title: "Latency",
                  desc: "Each event records the wall-clock duration in milliseconds when available.",
                },
                {
                  title: "Your metadata",
                  desc: "Feature, environment, user, session, tags, and extra JSON help you slice usage later.",
                },
              ].map((card) => (
                <div
                  key={card.title}
                  className="border-2 border-white/8 bg-white/[0.03] p-4 shadow-[4px_4px_0_0_#000]"
                >
                  <h3 className="text-[.82rem] font-bold uppercase tracking-[0.18em] text-[#f59e0b] mb-2">
                    {card.title}
                  </h3>
                  <p className="text-[.83rem] text-zinc-400 leading-relaxed">
                    {card.desc}
                  </p>
                </div>
              ))}
            </div>

            <SectionTitle accentColor="#fb7185">
              Provider constants
            </SectionTitle>
            <p className="text-[.88rem] text-zinc-400 leading-[1.8]">
              The SDK exports a tiny helper object if you prefer constants over
              raw strings.
            </p>
            <CodeBlock lang="python">{`from trackly import providers

print(providers.LANGCHAIN)  # "langchain"
print(providers.ANTHROPIC)  # "anthropic"
print(providers.OLLAMA)     # "ollama"
print(providers.GEMINI)     # "gemini"`}</CodeBlock>
          </>
        );

      case "Installation":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Setup
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Installation
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Install the core package first, then add only the provider SDKs
              you actually use.
            </p>

            <Step n={1} label="Install Trackly">
              <CodeBlock lang="bash">{`pip install trackly`}</CodeBlock>
            </Step>

            <Step n={2} label="Install LangChain integrations">
              <CodeBlock lang="bash">{`pip install "trackly[openai]"
pip install "trackly[anthropic]"
pip install "trackly[gemini]"
pip install "trackly[ollama]"
pip install "trackly[all]"`}</CodeBlock>
            </Step>

            <Step n={3} label="Install native SDKs when needed">
              <CodeBlock lang="bash">{`# Needed for Trackly(provider="anthropic")
pip install anthropic

# Needed for Trackly(provider="ollama")
pip install ollama

# Needed for Trackly(provider="gemini")
pip install google-genai`}</CodeBlock>
            </Step>

            <Callout type="warn">
              The native wrappers and the LangChain integrations are separate.
              For example, <Ic>trackly[ollama]</Ic> installs the LangChain
              adapter, while native <Ic>trackly.chat(...)</Ic> needs the
              official <Ic>ollama</Ic> package too.
            </Callout>
          </>
        );

      case "Quickstart":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              First request
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Quickstart
            </h1>

            <Step n={1} label="Create a Trackly API key">
              <p className="text-[.86rem] text-zinc-400 leading-[1.7]">
                In the dashboard, create an organization, create a project, and
                then generate a project-scoped API key.
              </p>
            </Step>

            <Step n={2} label="Export your key">
              <CodeBlock lang=".env">{`TRACKLY_API_KEY=tk_live_your_key_here`}</CodeBlock>
            </Step>

            <Step n={3} label="Attach Trackly to a LangChain model">
              <CodeBlock lang="python">{`from trackly import Trackly
from langchain_openai import ChatOpenAI

trackly = Trackly(
    feature="support-chat",
    environment="production",
)

llm = ChatOpenAI(
    model="gpt-4o",
    callbacks=[trackly.callback()],
)

response = llm.invoke("Summarize this customer issue in one sentence.")
print(response.content)

# Call shutdown() in short-lived scripts, tests, or serverless functions
trackly.shutdown()`}</CodeBlock>
            </Step>

            <Callout type="success">
              After that call finishes, Trackly enqueues an event with model,
              provider, token usage, latency, feature, environment, and a UTC
              timestamp.
            </Callout>
          </>
        );

      case "Trackly constructor":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              SDK entry point
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Trackly constructor
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              The <Ic>Trackly</Ic> class is the main entry point for callbacks,
              native providers, and the background worker.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly, providers

trackly = Trackly(
    provider=providers.GEMINI,
    api_key="tk_live_...",
    base_url="https://trackly.example.com/api/v1",
    debug=False,
    feature="batch-summarizer",
    environment="production",
    gemini_api_key="AIza...",
)`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">
              Constructor parameters
            </SectionTitle>
            <ParameterGrid items={CONSTRUCTOR_PARAMS} />
          </>
        );

      case "Environment variables":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Configuration
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Environment variables
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Every constructor setting that matters most can also be driven by
              environment variables.
            </p>
            <CodeBlock lang=".env">{`TRACKLY_API_KEY=tk_live_your_trackly_key
TRACKLY_BASE_URL=http://localhost:8000/api/v1
TRACKLY_DEBUG=1
GEMINI_API_KEY=AIza_your_gemini_key`}</CodeBlock>
            <ParameterGrid items={ENV_VARS} />
          </>
        );

      case "Callbacks":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              LangChain
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Callbacks
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              <Ic>trackly.callback()</Ic> returns the Trackly instance itself as
              a LangChain callback handler. It does not take per-call metadata,
              so set metadata on the constructor.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly

trackly = Trackly(
    feature="retrieval",
    environment="staging",
)

callback_handler = trackly.callback()`}</CodeBlock>

            <SectionTitle accentColor="#fb7185">
              How the callback works
            </SectionTitle>
            <div className="space-y-4 text-[.86rem] text-zinc-400 leading-[1.8]">
              <p>
                On <Ic>on_llm_start</Ic>, Trackly stores the start time and
                tries to capture the model name from LangChain invocation
                params.
              </p>
              <p>
                On <Ic>on_llm_end</Ic>, Trackly computes latency, token counts,
                finish reason, infers the provider, builds an event, and
                enqueues it for the background worker.
              </p>
              <p>
                On <Ic>on_llm_error</Ic>, Trackly only cleans up callback state.
                It does not emit a usage event for failed runs.
              </p>
            </div>

            <Callout type="info">
              For LangChain usage, you usually do not need to set
              <Ic>provider</Ic> at all. Trackly infers the provider from the
              serialized LangChain namespace and then falls back to the model
              name.
            </Callout>
          </>
        );

      case "LangChain provider examples":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Examples
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              LangChain provider examples
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              These examples all use the same Trackly pattern: construct one
              client, call <Ic>callback()</Ic>, and attach it to the LangChain
              model.
            </p>

            <div className="space-y-8">
              {LANGCHAIN_EXAMPLES.map((example) => (
                <div
                  key={example.title}
                  className="border-2 border-white/8 bg-white/[0.03] p-5 shadow-[4px_4px_0_0_#000]"
                >
                  <div className="flex flex-col gap-2 mb-3">
                    <h3 className="text-[.96rem] font-bold uppercase tracking-[0.14em] text-white">
                      {example.title}
                    </h3>
                    <p className="text-[.8rem] text-zinc-500">
                      Install: <Ic>{example.install}</Ic>
                    </p>
                  </div>
                  <CodeBlock lang="python">{example.code}</CodeBlock>
                </div>
              ))}
            </div>
          </>
        );

      case "Introduction to native SDKs":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Direct integration
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Native SDKs
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Trackly provides direct wrappers for official provider SDKs. This
              is the best way to track usage if you aren&apos;t using LangChain.
              When you use a native wrapper, Trackly automatically manages the
              underlying client and transparently logs events for you.
            </p>
            <Callout type="info">
              To use these, initialize Trackly with{" "}
              <Ic>provider=&quot;provider_name&quot;</Ic> and provide the
              corresponding API key.
            </Callout>
            <SectionTitle>Supported Individual SDKs</SectionTitle>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                { name: "Anthropic", desc: "Native messages API support" },
                { name: "Google Gemini", desc: "Models and Batches support" },
                { name: "Ollama", desc: "Local LLM tracking and management" },
              ].map((sdk) => (
                <div
                  key={sdk.name}
                  className="border-2 border-white/8 bg-white/[0.03] p-4 shadow-[4px_4px_0_0_#000]"
                >
                  <h3 className="text-[.82rem] font-bold uppercase tracking-[0.18em] text-white mb-2">
                    {sdk.name}
                  </h3>
                  <p className="text-[.83rem] text-zinc-400">{sdk.desc}</p>
                </div>
              ))}
            </div>
          </>
        );

      case "Anthropic messages":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Native wrapper
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Anthropic messages
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              When <Ic>provider=&quot;anthropic&quot;</Ic>, Trackly exposes
              <Ic>trackly.messages</Ic> and wraps the official
              <Ic>anthropic.resources.Messages</Ic> API. It records input
              tokens, output tokens, latency, stop reason, and message IDs.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly, providers
            
trackly = Trackly(
    provider=providers.ANTHROPIC,
    api_key="tk_live_...",
    anthropic_api_key="sk-ant-...",
    feature="customer-support",
)

response = trackly.messages.create(
    model="claude-3-5-sonnet-latest",
    max_tokens=1024,
    messages=[
        {"role": "user", "content": "Explain data observability in one sentence."}
    ],
)

print(response.content[0].text)`}</CodeBlock>

            <CodeBlock lang="python">{`import asyncio
from trackly import Trackly, providers

async def main():
    trackly = Trackly(provider=providers.ANTHROPIC)

    response = await trackly.messages.create_async(
        model="claude-3-sonnet-20240229",
        max_tokens=1024,
        messages=[{"role": "user", "content": "Hello!"}],
    )
    print(response.content[0].text)

asyncio.run(main())`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">Method parameters</SectionTitle>
            <ParameterGrid
              items={[
                {
                  name: "create(**kwargs)",
                  type: "official anthropic signals",
                  description:
                    "Synchronous message creation. Trackly times the call and logs usage from the final response object.",
                  example:
                    'trackly.messages.create(model="...", messages=[...])',
                },
                {
                  name: "create_async(**kwargs)",
                  type: "official anthropic signals",
                  description:
                    "Async message creation. Uses the Anthropic AsyncClient internally.",
                },
                {
                  name: "api_key",
                  type: "string | null",
                  description:
                    "Optional per-call override for the Anthropic API key.",
                },
              ]}
            />
          </>
        );

      case "Ollama native":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Native wrapper
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Ollama native
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              When <Ic>provider=&quot;ollama&quot;</Ic>, Trackly wraps the
              official
              <Ic>ollama</Ic> Python package and logs usage from chat, generate,
              and embed calls.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly, providers

trackly = Trackly(
    provider=providers.OLLAMA,
    api_key="tk_live_...",
    feature="local-chat",
    environment="dev",
)

chat_response = trackly.chat(
    model="llama3.2",
    messages=[
        {"role": "system", "content": "You answer in one short paragraph."},
        {"role": "user", "content": "Explain vector databases simply."},
    ],
)

generate_response = trackly.generate(
    model="llama3.2",
    prompt="Write a five-word slogan for Trackly.",
)

embedding_response = trackly.embed(
    model="nomic-embed-text",
    input="Track this paragraph for retrieval.",
)`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">
              Tracked Ollama methods
            </SectionTitle>
            <ParameterGrid
              items={[
                {
                  name: "chat(*args, **kwargs)",
                  type: "official ollama.chat signature",
                  description:
                    "Sends a chat request through Ollama. Trackly logs tokens and latency from the final response.",
                  example: 'trackly.chat(model="llama3.2", messages=[...])',
                },
                {
                  name: "generate(*args, **kwargs)",
                  type: "official ollama.generate signature",
                  description:
                    "Wraps text generation through Ollama and logs usage.",
                  example: 'trackly.generate(model="llama3.2", prompt="Hello")',
                },
                {
                  name: "embed(*args, **kwargs)",
                  type: "official ollama.embed signature",
                  description:
                    'Wraps embeddings and logs an event with `finish_reason="embedding"`.',
                  example:
                    'trackly.embed(model="nomic-embed-text", input="hello")',
                },
                {
                  name: "stream=True",
                  type: "bool",
                  description:
                    "When you stream chat or generate, Trackly waits for the final `done` chunk before logging usage.",
                  example: "trackly.chat(..., stream=True)",
                },
              ]}
            />

            <Callout type="info">
              Trackly forwards the original Ollama parameters unchanged. The
              most common ones you will pass are <Ic>model</Ic>,
              <Ic>messages</Ic>, <Ic>prompt</Ic>, <Ic>input</Ic>, and
              <Ic>stream</Ic>.
            </Callout>
          </>
        );

      case "Ollama async + utilities":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Async and utility methods
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Ollama async + utilities
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Async methods mirror the sync API and use the Ollama
              <Ic>AsyncClient</Ic>. Utility methods expose model management
              helpers from the Ollama SDK.
            </p>
            <CodeBlock lang="python">{`import asyncio
from trackly import Trackly, providers

async def main():
    trackly = Trackly(provider=providers.OLLAMA, feature="async-local")

    response = await trackly.chat_async(
        model="llama3.2",
        messages=[{"role": "user", "content": "Say hello in six words."}],
    )
    print(response["message"]["content"])

    stream = await trackly.generate_async(
        model="llama3.2",
        prompt="Write a short poem about telemetry.",
        stream=True,
    )

    async for chunk in stream:
        print(chunk.get("response", ""), end="")

    embeddings = await trackly.embed_async(
        model="nomic-embed-text",
        input="Track this asynchronously.",
    )
    print(len(embeddings["embeddings"]))

asyncio.run(main())`}</CodeBlock>

            <SectionTitle accentColor="#fb7185">
              Non-tracking utility methods
            </SectionTitle>
            <CodeBlock lang="python">{`from trackly import Trackly, providers

trackly = Trackly(provider=providers.OLLAMA)

models = trackly.list()
info = trackly.show("llama3.2")
running = trackly.ps()
trackly.pull("llama3.2")
trackly.push("my-custom-model")
trackly.copy("llama3.2", "llama3.2-backup")
trackly.create(model="qa-helper", from_="llama3.2")
trackly.delete("llama3.2-backup")`}</CodeBlock>
            <ParameterGrid
              items={[
                {
                  name: "list()",
                  type: "no parameters",
                  description: "Returns local Ollama models.",
                },
                {
                  name: "show(model)",
                  type: "model: string",
                  description: "Returns model metadata for one local model.",
                  example: 'trackly.show("llama3.2")',
                },
                {
                  name: "ps()",
                  type: "no parameters",
                  description: "Lists running models.",
                },
                {
                  name: "create(**kwargs)",
                  type: "official ollama.create signature",
                  description:
                    "Creates a model through Ollama. Trackly forwards all arguments unchanged.",
                  example:
                    'trackly.create(model="qa-helper", from_="llama3.2")',
                },
                {
                  name: "copy(source, destination)",
                  type: "source: string, destination: string",
                  description: "Copies a local model.",
                },
                {
                  name: "delete(model)",
                  type: "model: string",
                  description: "Deletes a local model.",
                },
                {
                  name: "pull(model, **kwargs)",
                  type: "model: string + Ollama kwargs",
                  description: "Pulls a remote model.",
                },
                {
                  name: "push(model, **kwargs)",
                  type: "model: string + Ollama kwargs",
                  description: "Pushes a local model to a registry.",
                },
              ]}
            />
            <Callout type="warn">
              Only chat, generate, embed, and their async variants emit Trackly
              usage events. Model management helpers are pass-through calls.
            </Callout>
          </>
        );

      case "Gemini models":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Native wrapper
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Gemini models
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              When <Ic>provider=&quot;gemini&quot;</Ic>, Trackly exposes
              <Ic>trackly.models</Ic> and wraps <Ic>google.genai.Client</Ic>. It
              records prompt tokens, candidate tokens, total tokens, latency,
              finish reason, feature, environment, and timestamp.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly, providers

trackly = Trackly(
    provider=providers.GEMINI,
    api_key="tk_live_...",
    gemini_api_key="AIza...",
    feature="summaries",
    environment="production",
)

response = trackly.models.generate_content(
    model="gemini-1.5-flash",
    contents="Explain quantum computing in one short paragraph.",
)

print(response.text)`}</CodeBlock>
            <CodeBlock lang="python">{`import asyncio
from trackly import Trackly, providers

async def main():
    trackly = Trackly(
        provider=providers.GEMINI,
        gemini_api_key="AIza...",
        feature="async-gemini",
    )

    response = await trackly.models.generate_content_async(
        model="gemini-1.5-flash",
        contents="Write a two-sentence release note.",
        api_key="AIza_per_call_override",
    )
    print(response.text)

asyncio.run(main())`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">Method parameters</SectionTitle>
            <ParameterGrid
              items={[
                {
                  name: "generate_content(model, contents, **kwargs)",
                  type: "model: str, contents: Any",
                  required: true,
                  description:
                    "Synchronous Gemini content generation. Trackly times the call, then logs usage from `response.usage_metadata`.",
                  example:
                    'trackly.models.generate_content(model="gemini-1.5-flash", contents="Hello")',
                },
                {
                  name: "generate_content_async(model, contents, **kwargs)",
                  type: "model: str, contents: Any",
                  required: true,
                  description:
                    "Async Gemini generation with the same tracked fields as the sync method.",
                },
                {
                  name: "model",
                  type: "string",
                  required: true,
                  description:
                    "Gemini model name. Trackly stores this exact string on the event.",
                },
                {
                  name: "contents",
                  type: "Any",
                  required: true,
                  description:
                    "Whatever the underlying Gemini SDK accepts for content input: plain text, structured content, or arrays.",
                },
                {
                  name: "api_key",
                  type: "string | null",
                  description:
                    "Optional per-call override. If omitted, Trackly uses `gemini_api_key` from the constructor or `GEMINI_API_KEY`.",
                  example: 'api_key="AIza_override"',
                },
                {
                  name: "**kwargs",
                  type: "provider-specific options",
                  description:
                    "Forwarded directly into `client.models.generate_content(...)`.",
                  example: 'config={"temperature": 0.2}',
                },
              ]}
            />
          </>
        );

      case "Gemini batches":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Batch operations
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Gemini batches
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Trackly exposes <Ic>trackly.batches</Ic> for batch creation,
              embedding batch creation, status checks, listing, canceling, and
              deleting. Batch events use provider <Ic>google-batch</Ic>.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly, providers

trackly = Trackly(
    provider=providers.GEMINI,
    gemini_api_key="AIza...",
    feature="offline-processing",
)

job = trackly.batches.create(
    model="gemini-1.5-flash",
    src="gs://my-bucket/prompts.jsonl",
    config={"dest": "gs://my-bucket/results/"},
)

embedding_job = trackly.batches.create_embeddings(
    model="text-embedding-004",
    src="gs://my-bucket/embedding-input.jsonl",
    config={"dest": "gs://my-bucket/embedding-output/"},
)

status = trackly.batches.get(name=job.name)
jobs = trackly.batches.list(page_size=20)
trackly.batches.cancel(name=job.name)
trackly.batches.delete(name=job.name)`}</CodeBlock>

            <SectionTitle accentColor="#fb7185">
              Batch method parameters
            </SectionTitle>
            <ParameterGrid
              items={[
                {
                  name: "create(model, src, config=None, **kwargs)",
                  type: "model: str, src: Any, config: dict | None",
                  description:
                    "Creates a Gemini batch job and logs an action of `create`.",
                },
                {
                  name: "create_embeddings(model, src, config=None, **kwargs)",
                  type: "model: str, src: Any, config: dict | None",
                  description:
                    "Creates a Gemini embeddings batch and logs `create_embeddings`.",
                },
                {
                  name: "get(name, **kwargs)",
                  type: "name: str",
                  description:
                    "Fetches a batch job. When the returned state is `JOB_STATE_SUCCEEDED`, Trackly logs `status_check`.",
                },
                {
                  name: "list(**kwargs)",
                  type: "provider-specific list kwargs",
                  description: "Lists Gemini batch jobs.",
                },
                {
                  name: "cancel(name, **kwargs)",
                  type: "name: str",
                  description: "Cancels a batch job.",
                },
                {
                  name: "delete(name, **kwargs)",
                  type: "name: str",
                  description: "Deletes a batch job.",
                },
                {
                  name: "api_key",
                  type: "string | null",
                  description:
                    "Optional per-call Gemini API key override on every batch method.",
                },
              ]}
            />
          </>
        );

      case "Debug and shutdown":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Runtime behavior
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Debug and shutdown
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Trackly ships events in a background thread every two seconds,
              retries failed sends up to three times, and keeps a queue of up to
              5000 events.
            </p>
            <CodeBlock lang="python">{`from trackly import Trackly

trackly = Trackly(debug=True)

# ... your model calls ...

trackly.shutdown(timeout=5.0)`}</CodeBlock>
            <ParameterGrid
              items={[
                {
                  name: "debug",
                  type: "bool",
                  defaultValue: "False",
                  description:
                    "Prints worker warnings, queued events, retry failures, and HTTP status codes.",
                },
                {
                  name: "shutdown(timeout=5.0)",
                  type: "timeout: float",
                  description:
                    "Flushes any queued events and waits for the worker thread to stop.",
                  example: "trackly.shutdown(timeout=2.0)",
                },
              ]}
            />
            <Callout type="warn">
              In long-running web servers you can usually rely on the background
              thread and the <Ic>atexit</Ic> shutdown hook. In tests, CLI tools,
              and serverless functions, call <Ic>shutdown()</Ic> yourself.
            </Callout>
          </>
        );

      case "Ingest API":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Backend API
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Ingest API
            </h1>
            <RouteBadge>POST /api/v1/events</RouteBadge>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mt-6 mb-6">
              The Trackly SDK uses this route automatically. If you want to send
              manual events, wrap them in an <Ic>events</Ic> array. The backend
              accepts between 1 and 100 events per request.
            </p>
            <CodeBlock lang="bash">{`curl -X POST http://localhost:8000/api/v1/events \\
  -H "Authorization: Bearer tk_live_your_key_here" \\
  -H "Content-Type: application/json" \\
  -d '{
    "events": [
      {
        "provider": "openai",
        "model": "gpt-4o",
        "prompt_tokens": 1200,
        "completion_tokens": 280,
        "latency_ms": 842,
        "finish_reason": "stop",
        "feature": "invoice-summary",
        "user_id": "auth0|abc123",
        "session_id": "chat-session-44",
        "environment": "production",
        "tags": ["beta", "priority-customer"],
        "extra": {"route": "/chat"},
        "timestamp": "2026-03-25T19:15:00Z"
      }
    ]
  }'`}</CodeBlock>
            <CodeBlock lang="json">{`{
  "accepted": 1,
  "rejected": 0
}`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">
              Event payload fields
            </SectionTitle>
            <ParameterGrid items={INGEST_FIELDS} />
          </>
        );

      case "Events API":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Query raw events
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Events API
            </h1>
            <RouteBadge>
              GET /api/v1/projects/{`{project_id}`}/events
            </RouteBadge>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mt-6 mb-6">
              This endpoint returns raw events with pagination and filters.
            </p>
            <CodeBlock lang="bash">{`curl "http://localhost:8000/api/v1/projects/6f3b3f0b-1234-5678-9abc-def012345678/events?feature=support-chat&provider=openai&page=1&page_size=20"`}</CodeBlock>
            <CodeBlock lang="json">{`{
  "items": [
    {
      "id": "1dfe09a1-1234-5678-9abc-def012345678",
      "provider": "openai",
      "model": "gpt-4o",
      "prompt_tokens": 1200,
      "completion_tokens": 280,
      "total_tokens": 1480,
      "estimated_cost_usd": 0.0123,
      "latency_ms": 842,
      "finish_reason": "stop",
      "feature": "support-chat",
      "user_id": "auth0|abc123",
      "session_id": "chat-session-44",
      "run_id": "run_123",
      "tags": ["beta"],
      "occurred_at": "2026-03-25T19:15:00Z",
      "ingested_at": "2026-03-25T19:15:02Z",
      "user_name": "Taylor Kim",
      "user_photo": null,
      "api_key_id": "6f3b3f0b-1234-5678-9abc-def012345678",
      "parent_api_key_id": null
    }
  ],
  "total": 1,
  "page": 1,
  "page_size": 20,
  "has_more": false
}`}</CodeBlock>

            <SectionTitle accentColor="#fb7185">Query parameters</SectionTitle>
            <ParameterGrid items={EVENTS_QUERY_PARAMS} />
          </>
        );

      case "Stats API":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Aggregates
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Stats API
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              Trackly exposes four project-level stats routes and one global
              route for platform counters.
            </p>
            <div className="space-y-3 mb-6 text-[.84rem] text-zinc-300">
              <RouteBadge>
                GET /api/v1/projects/{`{project_id}`}/stats/summary
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/projects/{`{project_id}`}/stats/by-model
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/projects/{`{project_id}`}/stats/by-feature
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/projects/{`{project_id}`}/stats/daily
              </RouteBadge>
              <RouteBadge>GET /api/v1/stats/global</RouteBadge>
            </div>

            <CodeBlock lang="bash">{`curl "http://localhost:8000/api/v1/projects/6f3b3f0b-1234-5678-9abc-def012345678/stats/summary?provider=openai&start=2026-03-01T00:00:00Z&end=2026-03-25T00:00:00Z"`}</CodeBlock>
            <CodeBlock lang="json">{`{
  "total_events": 248,
  "total_tokens": 812340,
  "total_cost_usd": 34.77,
  "avg_latency_ms": 623.9,
  "period_start": "2026-03-01T00:00:00Z",
  "period_end": "2026-03-25T00:00:00Z"
}`}</CodeBlock>
            <CodeBlock lang="bash">{`curl "http://localhost:8000/api/v1/projects/6f3b3f0b-1234-5678-9abc-def012345678/stats/daily"`}</CodeBlock>
            <CodeBlock lang="json">{`[
  {
    "date": "2026-03-24",
    "event_count": 18,
    "total_tokens": 62100,
    "total_cost_usd": 2.91
  },
  {
    "date": "2026-03-25",
    "event_count": 23,
    "total_tokens": 71140,
    "total_cost_usd": 3.44
  }
]`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">Query parameters</SectionTitle>
            <ParameterGrid items={STATS_QUERY_PARAMS} />

            <Callout type="info">
              If you omit <Ic>start</Ic> and <Ic>end</Ic>, Trackly uses the last
              30 days by default.
            </Callout>
          </>
        );

      case "Organizations and projects":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Workspace management
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Organizations and projects
            </h1>
            <div className="space-y-3 mb-6 text-[.84rem] text-zinc-300">
              <RouteBadge>POST /api/v1/organizations</RouteBadge>
              <RouteBadge>GET /api/v1/organizations/{`{org_id}`}</RouteBadge>
              <RouteBadge>
                POST /api/v1/organizations/{`{org_id}`}/projects
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/organizations/{`{org_id}`}/projects
              </RouteBadge>
              <RouteBadge>GET /api/v1/projects/{`{project_id}`}</RouteBadge>
              <RouteBadge>
                GET /api/v1/projects/{`{project_id}`}/members
              </RouteBadge>
              <RouteBadge>
                POST /api/v1/projects/{`{project_id}`}/members
              </RouteBadge>
              <RouteBadge>
                DELETE /api/v1/projects/{`{project_id}`}/members/{`{user_id}`}
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/organizations/{`{org_id}`}/users
              </RouteBadge>
              <RouteBadge>
                POST /api/v1/organizations/{`{org_id}`}/users
              </RouteBadge>
              <RouteBadge>
                GET /api/v1/organizations/{`{org_id}`}/usage
              </RouteBadge>
            </div>

            <CodeBlock lang="bash">{`curl -X POST http://localhost:8000/api/v1/organizations \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Acme AI",
    "slug": "acme-ai"
  }'

curl -X POST http://localhost:8000/api/v1/organizations/6f3b3f0b-1234-5678-9abc-def012345678/projects \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Production",
    "environment": "prod"
  }'`}</CodeBlock>

            <SectionTitle accentColor="#fb7185">
              Request body fields
            </SectionTitle>
            <ParameterGrid items={ORG_AND_PROJECT_FIELDS} />
          </>
        );

      case "API keys":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Authentication
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              API keys
            </h1>
            <div className="space-y-3 mb-6 text-[.84rem] text-zinc-300">
              <RouteBadge>
                POST /api/v1/organizations/{`{org_id}`}/api-keys
              </RouteBadge>
              <RouteBadge>POST /api/v1/api-keys/{`{key_id}`}/access</RouteBadge>
              <RouteBadge>
                GET /api/v1/organizations/{`{org_id}`}/api-keys
              </RouteBadge>
              <RouteBadge>DELETE /api/v1/api-keys/{`{key_id}`}</RouteBadge>
            </div>

            <CodeBlock lang="bash">{`curl -X POST http://localhost:8000/api/v1/organizations/6f3b3f0b-1234-5678-9abc-def012345678/api-keys \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Production server key",
    "project_id": "d36af0e5-1234-5678-9abc-def012345678"
  }'`}</CodeBlock>
            <CodeBlock lang="json">{`{
  "id": "8ac5dbd6-1234-5678-9abc-def012345678",
  "name": "Production server key",
  "key_prefix": "tk_live_ab12",
  "project_id": "d36af0e5-1234-5678-9abc-def012345678",
  "created_by_user_id": null,
  "parent_key_id": null,
  "is_active": true,
  "created_at": "2026-03-25T19:15:00Z",
  "last_used_at": null,
  "raw_key": "tk_live_0123456789abcdef0123456789abcdef"
}`}</CodeBlock>
            <CodeBlock lang="bash">{`curl -X POST http://localhost:8000/api/v1/api-keys/8ac5dbd6-1234-5678-9abc-def012345678/access \\
  -H "Content-Type: application/json" \\
  -d '{
    "auth0_id": "auth0|abc123"
  }'`}</CodeBlock>

            <SectionTitle accentColor="#14b8a6">
              Parameters and behavior
            </SectionTitle>
            <ParameterGrid items={API_KEY_FIELDS} />

            <Callout type="warn">
              The raw API key is only returned once when the key is created. The
              list endpoint never returns <Ic>raw_key</Ic>.
            </Callout>
          </>
        );

      case "Self-hosting":
        return (
          <>
            <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f59e0b] mb-4">
              Backend setup
            </p>
            <h1 className="text-[2.6rem] font-extrabold tracking-tighter leading-none mb-6 uppercase text-white">
              Self-hosting
            </h1>
            <p className="text-[.95rem] text-zinc-300 leading-[1.8] mb-6">
              The repository contains both the SDK and the FastAPI backend. For
              local development, start PostgreSQL first, then run the API.
            </p>
            <CodeBlock lang="bash">{`docker-compose up -d db

# in another shell
uvicorn app.main:app --host 0.0.0.0 --port 8000`}</CodeBlock>
            <CodeBlock lang=".env">{`DATABASE_URL=postgresql+asyncpg://postgres:1234@localhost:5432/trackly
ADMIN_API_TOKEN=your_admin_token
APP_BASE_URL=https://tracklyai.in
SUPPORT_EMAIL=support@tracklyai.in`}</CodeBlock>
            <Callout type="info">
              Once the backend is running, FastAPI docs are available at
              <Ic>/docs</Ic> and <Ic>/redoc</Ic>, and the health route is
              <Ic>/health</Ic>.
            </Callout>
          </>
        );

      default:
        return <p className="text-zinc-400">Section coming soon.</p>;
    }
  };

  return (
    <div className="flex flex-col min-h-screen bg-[#06070c] selection:bg-[#f59e0b]/30 scroll-smooth relative overflow-hidden docs-root">
      <style>{`
        .docs-root::before {
          content:'';
          position:absolute;
          inset:0;
          background-image:
            linear-gradient(rgba(25, 97, 240, 0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(31, 20, 184, 0.05) 1px, transparent 1px);
          background-size: 56px 56px;
          mask-image: radial-gradient(ellipse 80% 70% at 50% 0%, black 30%, transparent 100%);
          pointer-events:none;
          z-index:0;
        }
        .orb {
          position:absolute;
          border-radius:50%;
          filter:blur(120px);
          pointer-events:none;
          z-index:0;
        }
        .orb-1 {
          width:560px;
          height:560px;
          background: oklch(0.398 0.195 277.366);
          top:-180px;
          left:-180px;
          opacity:0.10;
        }
        .orb-2 {
          width:460px;
          height:460px;
          background:#14b8a6;
          top:80px;
          right:-120px;
          opacity:0.08;
        }
        .no-scrollbar::-webkit-scrollbar {
          display:none;
        }
        .no-scrollbar {
          -ms-overflow-style:none;
          scrollbar-width:none;
        }
      `}</style>

      <div className="orb orb-1" />
      <div className="orb orb-2" />

      <Header />

      <div className="flex-1 flex flex-col md:flex-row max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 pt-24 pb-12 gap-6 md:gap-12 relative z-10">
        <div className="md:hidden sticky top-20 z-30 flex items-center gap-2 px-4 py-3 bg-[#06070c]/85 backdrop-blur-md border-2 border-white/8 mb-4 shadow-[4px_4px_0_0_#000]">
          <Sheet open={isSidebarOpen} onOpenChange={setIsSidebarOpen}>
            <SheetTrigger asChild>
              <button className="flex items-center gap-2 text-zinc-400 hover:text-white transition-colors cursor-pointer">
                <List size={20} weight="bold" />
                <span className="text-[10px] font-bold uppercase tracking-wider">
                  Docs
                </span>
              </button>
            </SheetTrigger>
            <SheetContent
              side="left"
              className="w-[300px] bg-[#06070c] border-r border-white/8 p-6 overflow-y-auto no-scrollbar"
            >
              <div className="mb-8">
                <Link className="text-white flex gap-2 items-center" href="/">
                  <Image
                    src="/logo/logo-48.png"
                    className="w-6 h-6"
                    alt="Trackly"
                    width={24}
                    height={24}
                  />
                  <h1 className="font-bold text-lg tracking-tight">Trackly</h1>
                </Link>
              </div>
              <DocsNav
                activeNav={activeNav}
                setActiveNav={setActiveNav}
                onItemSelected={() => setIsSidebarOpen(false)}
              />
            </SheetContent>
          </Sheet>
          <div className="h-4 w-px bg-white/10 mx-1" />
          <span className="text-[10px] font-bold text-[#f59e0b] uppercase tracking-[0.2em] truncate">
            {activeNav}
          </span>
        </div>

        <aside className="w-72 hidden md:block shrink-0 sticky top-24 h-[calc(100vh-8rem)] overflow-y-auto no-scrollbar pr-5 border-r border-white/8">
          <DocsNav activeNav={activeNav} setActiveNav={setActiveNav} />
        </aside>

        <main className="flex-1 min-w-0 max-w-4xl animate-in fade-in slide-in-from-bottom-4 duration-500">
          {renderContent()}
        </main>
      </div>

      <Footer />
    </div>
  );
}
